services:
  dns-proxy:
    build: .
    container_name: dns_proxy
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    depends_on:
      - elasticsearch
    cap_add:
      - NET_ADMIN    # Add necessary capabilities to bind to port 53
    networks:
      - dns_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    networks:
      - dns_network
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    container_name: kibana
    depends_on:
      - elasticsearch
    volumes:
      - kibana_config:/usr/share/kibana/config
    networks:
      - dns_network
    ports:
      - "5601:5601"
    restart: unless-stopped

networks:
  dns_network:
    driver: bridge

volumes:
  es_data:
    driver: local
  kibana_config:
    driver: local
